version: '3'
services:
  api:
    build: .
    container_name: aplicationProduct
    ports:
          - 8080:8080
    depends_on:
          - docker-mysql
    networks:
      - net
  docker-mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dbmysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodados
    networks:
      - net
  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - net

networks:
  net:
    driver: bridge